=== adehaan/WDI-Project/Mapping/Games.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Games">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Game" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Rank">
								<xs:complexType>
								</xs:complexType>
							</xs:element>
							<xs:element name="Title" type="xs:string"/>
							<xs:element name="Year" type="xs:string"/>
							<xs:element name="Sale_EU" type="xs:double"/>
							<xs:element name="Sale_JP" type="xs:double"/>
							<xs:element name="Sale_NA" type="xs:double"/>
							<xs:element name="Sale_Others" type="xs:double"/>
							<xs:element name="Sale_Global" type="xs:double"/>
							<xs:element name="Total_Length_in_hrs" type="xs:short"/>
							<xs:element name="Recommended_Req_PC" type="xs:string"/>
							<xs:element name="Website">
								<xs:complexType>
								</xs:complexType>
							</xs:element>
							<xs:element name="Country_of_Origin">
								<xs:complexType>
								</xs:complexType>
							</xs:element>
							<xs:element name="Sequel">
								<xs:complexType>
								</xs:complexType>
							</xs:element>
							<xs:element name="Prequel">
								<xs:complexType>
								</xs:complexType>
							</xs:element>
							<xs:element name="Stores">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Store" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" use="required" type="xs:string"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Age_groups">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Age_group" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" use="required" type="xs:string"/>
												<xs:attribute name="name" use="required" type="xs:string"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Rating">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Metacrtic" type="xs:decimal"/>
										<xs:element name="RAWG_Rating" type="xs:decimal"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Publishers">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Publisher" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="DeveloperStudios">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="DeveloperStudio" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Genres">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Genre" maxOccurs="unbounded" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="platforms">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="platform" maxOccurs="unbounded" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Modes">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Mode" maxOccurs="unbounded" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Tags">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Tag" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name" type="xs:string"/>
													<xs:element name="Games_count" type="xs:byte"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Contributors" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Contributor" maxOccurs="unbounded">
											<xs:complexType>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" use="required" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== adehaan/WDI-Project/IR/vg_IR/data/input/target_games_Wiki_empty_platforms.xml
<?xml version="1.0" encoding="UTF-8"?>
<Games xsi:noNamespaceSchemaLocation="file:///C:/Personel/Experience/WDI-Project/Mapping/Games.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	
	<Game>
		<id>wiki_16605</id>
		<Title>Injustice 2 Mobile</Title>
		<Year>2017</Year>
		<Website>https://www.injustice.com/mobile</Website>
		<Countries_of_Origin>
			<Country_of_Origin></Country_of_Origin>
		</Countries_of_Origin>
		<Sequel></Sequel>
		<Prequel></Prequel>
		<ESRBs/>
		<PEGIs/>
		<CEROs/>
		<Publishers>
			<Publisher></Publisher>
		</Publishers>
		<DeveloperStudios>
			<DeveloperStudio></DeveloperStudio>
		</DeveloperStudios>
		<Genres>
			<Genre></Genre>
		</Genres>
		<platforms>
			<platform></platform>
		</platforms>
		<Modes>
			<Mode></Mode>
		</Modes>
		<Contributors/>
	</Game>
	<Game>
		<id>wiki_16606</id>
		<Title>I Love You!</Title>
		<Year>0001</Year>
		<Website></Website>
		<Countries_of_Origin>
			<Country_of_Origin>Japan</Country_of_Origin>
		</Countries_of_Origin>
		<Sequel></Sequel>
		<Prequel></Prequel>
		<ESRBs/>
		<PEGIs/>
		<CEROs/>
		<Publishers>
			<Publisher></Publisher>
		</Publishers>
		<DeveloperStudios>
			<DeveloperStudio></DeveloperStudio>
		</DeveloperStudios>
		<Genres>
			<Genre>hentai</Genre>
		</Genres>
		<platforms>
			<platform></platform>
		</platforms>
		<Modes>
			<Mode></Mode>
		</Modes>
		<Contributors/>
	</Game>
</Games>

=== adehaan/WDI-Project/IR/goldstandard_fusion2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Games xsi:noNamespaceSchemaLocation="file:///C:/Personel/Experience/WDI-Project/Mapping/Games.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Game>
		<id>sales_1</id>
		<Title>Wii Sports</Title>
		<Year>2006</Year>
		<Publishers>
			<Publisher>Nintendo</Publisher>
		</Publishers>
		<Genres>
			<Genre>Sports</Genre>
			<Genre>Bowling</Genre>
			<Genre>Boxing</Genre>
			<Genre>Tennis</Genre>
			<Genre>Baseball Arcade</Genre>
			<Genre>Golf Arcade</Genre>
		</Genres>
		<platforms>
			<platform>Nintendo Wii</platform>
		</platforms>
	</Game>
	<Game>
		<id>sales_2</id>
		<Title>Super Mario Bros.</Title>
		<Year>1985</Year>
		<Publishers>
			<Publisher>Nintendo</Publisher>
		</Publishers>
		<Genres>
			<Genre>Platform</Genre>
			<Genre>Action</Genre>
		</Genres>
		<platforms>
			<platform>Nintendo Entertainment System</platform>
		</platforms>
	</Game>
	<Game>
		<id>sales_3</id>
		<Title>Mario Kart Wii</Title>
		<Year>2008</Year>
		<Publishers>
			<Publisher>Nintendo</Publisher>
		</Publishers>
		<Genres>
			<Genre>cart race</Genre>
		</Genres>
		<platforms>
			<platform>Nintendo Wii</platform>
		</platforms>
	</Game>	
	<Game>
		<id>sales_6</id>
		<Rank/>
		<Title>Tetris</Title>
		<Year>1989</Year>
		<Publishers>
			<Publisher>Nintendo</Publisher>
		</Publishers>
		<Genres>
			<Genre>Puzzle</Genre>
		</Genres>
		<platforms>
			<platform>Nintendo Entertainment System</platform>
		</platforms>
	</Game>
	<Game>
		<id>sales_11</id>
		<Title>Nintendogs</Title>
		<Year>2005</Year>
		<Publishers>
			<Publisher>Nintendo</Publisher>
		</Publishers>
		<Genres>
			<Genre>Simulation</Genre>
		</Genres>
		<platforms>
			<platform>DS</platform>
		</platforms>
	</Game>
	<Game>
		<id>sales_16</id>
		<Title>Kinect Adventures!</Title>
		<Year>2010</Year>
		<Publishers>
			<Publisher>Microsoft Game Studios</Publisher>
		</Publishers>
		<Genres>
			<Genre>Sports</Genre>
		</Genres>
		<platforms>
			<platform>Xbox 360</platform>
		</platforms>
	</Game>	
	<Game>
		<id>sales_17</id>
		<Title>Grand Theft Auto V</Title>
		<Year>2013</Year>
		<Publishers>
			<Publisher>Rockstar Games</Publisher>
		</Publishers>
		<Genres>
			<Genre>Action-Adventure</Genre>
		</Genres>
		<platforms>
			<platform>PC</platform>
			<platform>PlayStation 3</platform>
			<platform>PlayStation 4</platform>
			<platform>Xbox 360</platform>
			<platform>Xbox One</platform>
		</platforms>
	</Game>
	<Game>
		<id>sales_32</id>
		<Title>Call of Duty: Black Ops</Title>
		<Year>2010</Year>
		<Publishers>
			<Publisher>Activision Blizzard</Publisher>
		</Publishers>
		<Genres>
			<Genre>Ego Shooter</Genre>
			<Genre>Action</Genre>
		</Genres>
		<platforms>
			<platform>Xbox 360</platform>
		</platforms>
	</Game>
	<Game>
		<id>sales_39</id>
		<Title>Grand Theft Auto III</Title>
		<Year>2001</Year>
		<Publishers>
			<Publisher>Rockstar Games</Publisher>
		</Publishers>
		<Genres>
			<Genre>Action</Genre>
			<Genre>Open World</Genre>
			<Genre>Automobile Sim</Genre>
		</Genres>
		<platforms>
			<platform>PlayStation 2</platform>
		</platforms>
	</Game>
	<Game>
		<id>sales_42</id>
		<Title>Animal Crossing: Wild World</Title>
		<Year>2005</Year>
		<Publishers>
			<Publisher>Nintendo</Publisher>
		</Publishers>
		<Genres>
			<Genre>Life simulation</Genre>
		</Genres>
		<platforms>
			<platform>Nintendo DS</platform>
		</platforms>
	</Game>
	<Game>
		<id>sales_44</id>
		<Title>Halo 3</Title>
		<Year>2007</Year>
		<Publishers>
			<Publisher>Microsoft Game Studios</Publisher>
		</Publishers>
		<Genres>
			<Genre>Shooter</Genre>
			<Genre>First-person shooter</Genre>
		</Genres>
		<platforms>
			<platform>Xbox 360</platform>
		</platforms>
	</Game>
	<Game>
		<id>sales_69</id>
		<Title>Just Dance 2</Title>
		<Year>2010</Year>
		<Publishers>
			<Publisher>Ubisoft</Publisher>
		</Publishers>
		<Genres>
			<Genre>Dance</Genre>
			<Genre>Rhythm</Genre>
		</Genres>
		<platforms>
			<platform>Wii</platform>
		</platforms>
	</Game>
	<Game>
		<id>sales_78</id>
		<Title>FIFA 16</Title>
		<Year>2015</Year>
		<Publishers>
			<Publisher>Electronic Arts</Publisher>
		</Publishers>
		<Genres>
			<Genre>Sports</Genre>
		</Genres>
		<platforms>
			<platform>PlayStation 4</platform>
			<platform>PlayStation 3</platform>
			<platform>Xbox 360</platform>
			<platform>Xbox One</platform>
		</platforms>
	</Game>
	<Game>
		<id>sales_105</id>
		<Title>Need for Speed: Underground</Title>
		<Year>2003</Year>
		<Publishers>
			<Publisher>Electronic Arts</Publisher>
		</Publishers>
		<Genres>
			<Genre>Racing</Genre>
			<Genre>Arcade</Genre>
		</Genres>
		<platforms>
			<platform>PlayStation 2</platform>
			<platform>Xbox</platform>
			<platform>PC</platform>
		</platforms>
	</Game>
		<Game>
		<id>sales_110</id>
		<Title>Fallout 4</Title>
		<Year>2015</Year>
		<Publishers>
			<Publisher>Bethesda Softworks</Publisher>
		</Publishers>
		<Genres>
			<Genre>Role-Playing</Genre>
		</Genres>
		<platforms>
			<platform>PlayStation 4</platform>
			<platform>Microsoft Windows</platform>
			<platform>Xbox One</platform>
		</platforms>
	</Game>
	<Game>
		<id>sales_593</id>
		<Title>LittleBigPlanet</Title>
		<Year>2008</Year>
		<Publishers>
			<Publisher>Sony Computer Entertainment</Publisher>
		</Publishers>
		<Genres>
			<Genre>Action</Genre>
			<Genre>Puzzle</Genre>
			<Genre>Family</Genre>
		</Genres>
		<platforms>
			<platform>PlayStation 3</platform>
		</platforms>
	</Game>
	<Game>
		<id>sales_4269</id>
		<Title>The Mark of Kri</Title>
		<Year>2002</Year>
		<Publishers>
			<Publisher>Sony Computer Entertainment</Publisher>
		</Publishers>
		<Genres>
			<Genre>Action-adventure</Genre>
		</Genres>
		<platforms>
			<platform>PlayStation 2</platform>
		</platforms>
	</Game>
	<Game>
		<id>sales_5911</id>
		<Title>Spider-Man: Friend or Foe</Title>
		<Year>2007</Year>
		<Publishers>
			<Publisher>Activision</Publisher>
		</Publishers>
		<Genres>
			<Genre>Action</Genre>
		</Genres>
		<platforms>
			<platform>PlayStation 2</platform>
			<platform>Xbox 360</platform>
			<platform>Wii</platform>
			<platform>PlayStation 2</platform>
			<platform>PlayStation Portable</platform>
			<platform>Nintendo DS</platform>
			<platform>Microsoft Windows</platform>
		</platforms>
	</Game>
	<Game>
		<id>sales_3981</id>
		<Title>Fortune Street</Title>
		<Year>2011</Year>
		<Publishers>
			<Publisher>Nintendo</Publisher>
		</Publishers>
		<Genres>
			<Genre>Plattform</Genre>
		</Genres>
		<platforms>
			<platform>Wii</platform>
		</platforms>
	</Game>
	<Game>
		<id>sales_13346</id>
		<Title>Bubble Bobble Revolution</Title>
		<Year>2005</Year>
		<Publishers>
			<Publisher>Taito</Publisher>
			<Publisher>Rising Star Games</Publisher>
			<Publisher>Codemasters</Publisher>
		</Publishers>
		<Genres>
			<Genre>Plattform</Genre>
			<Genre>Puzzle</Genre>
		</Genres>
		<platforms>
			<platform>Nintendo DS</platform>
		</platforms>
	</Game>
</Games>

=== adehaan/WDI-Project/IR/vg_IR/data/input/sales_target_test empty files.xml
<?xml version="1.0" encoding="UTF-8"?>
<Games xsi:noNamespaceSchemaLocation="file:///C:/Personel/Experience/WDI-Project/Mapping/Games.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Game>
		<id>sales_1304</id>
		<Rank/>
		<Title>Triple Play 99</Title>
		<Year></Year>
		<Sale_EU>0.55</Sale_EU>
		<Sale_JP>0</Sale_JP>
		<Sale_NA>0.81</Sale_NA>
		<Sale_Others>0.1</Sale_Others>
		<Sale_Global>1.46</Sale_Global>
		<Publishers>
			<Publisher>N/A</Publisher>
		</Publishers>
		<Genres>
			<Genre>Sports</Genre>
		</Genres>
		<platforms>
			<platform>PS</platform>
		</platforms>
	</Game>	
	<Game>
		<id>sales_1663</id>
		<Rank/>
		<Title>Shrek / Shrek 2 2-in-1 Gameboy Advance Video</Title>
		<Year>2007</Year>
		<Sale_EU>0.32</Sale_EU>
		<Sale_JP>0</Sale_JP>
		<Sale_NA>0.87</Sale_NA>
		<Sale_Others>0.02</Sale_Others>
		<Sale_Global>1.21</Sale_Global>
		<Publishers>
			<Publisher>N/A</Publisher>
		</Publishers>
		<Genres>
			<Genre>Misc</Genre>
		</Genres>
		<platforms>
			<platform>GBA</platform>
		</platforms>
	</Game>
</Games>
